services:
  - type: web
    name: road-complaint-and-monitoring-system
    runtime: node
    buildCommand: cd backend && npm install && cd ../frontend && npm install && npm run build && cd ../backend
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
